export { default as LoginPage } from './LoginPage';
export { default as HomePage } from './HomePage';
export { default as NotFoundPage } from './NotFoundPage';
export * from './Admin';
export { default as ForbiddenPage } from './ForbiddenPage';
export { default as BuyPage } from './BuyPage';
export { default as SignUpPage } from './SignUpPage';
export { default as ResetPasswordPage } from './ChangePasswordPage';
export { default as ForgotPasswordPage } from './ForgotPasswordPage';
export { default as VoiceGeneratorPage } from './VoiceGeneratorPage';
